//
// Created by cpasjuste on 22/03/23.
//

// from https://github.com/torvalds/linux/blob/master/drivers/input/joystick/xpad.c

#include "devices.h"

#define MAP_DPAD_TO_BUTTONS     (1 << 0)
#define MAP_TRIGGERS_TO_BUTTONS (1 << 1)
#define MAP_STICKS_TO_NULL      (1 << 2)
#define MAP_SELECT_BUTTON       (1 << 3)
#define MAP_PADDLES             (1 << 4)
#define MAP_PROFILE_BUTTON      (1 << 5)

#define DANCEPAD_MAP_CONFIG     (MAP_DPAD_TO_BUTTONS | MAP_TRIGGERS_TO_BUTTONS | MAP_STICKS_TO_NULL)

const Device devices[] = {
        ///
        /// XBOX
        ///
        {0x0079, 0x18d4, (char *) "GPD Win 2 X-Box Controller",                           0,                 TYPE_XBOX360},
        {0x03eb, 0xff01, (char *) "Wooting One (Legacy)",                                 0,                 TYPE_XBOX360},
        {0x03eb, 0xff02, (char *) "Wooting Two (Legacy)",                                 0,                 TYPE_XBOX360},
        {0x044f, 0x0f00, (char *) "Thrustmaster Wheel",                                   0,                 TYPE_XBOX},
        {0x044f, 0x0f03, (char *) "Thrustmaster Wheel",                                   0,                 TYPE_XBOX},
        {0x044f, 0x0f07, (char *) "Thrustmaster, Inc. Controller",                        0,                 TYPE_XBOX},
        {0x044f, 0x0f10, (char *) "Thrustmaster Modena GT Wheel",                         0,                 TYPE_XBOX},
        {0x044f, 0xb326, (char *) "Thrustmaster Gamepad GP XID",                          0,                 TYPE_XBOX360},
        {0x045e, 0x0202, (char *) "Microsoft X-Box pad v1 (US)",                          0,                 TYPE_XBOX},
        {0x045e, 0x0285, (char *) "Microsoft X-Box pad (Japan)",                          0,                 TYPE_XBOX},
        {0x045e, 0x0287, (char *) "Microsoft Xbox Controller S",                          0,                 TYPE_XBOX},
        {0x045e, 0x0288, (char *) "Microsoft Xbox Controller S v2",                       0,                 TYPE_XBOX},
        {0x045e, 0x0289, (char *) "Microsoft X-Box pad v2 (US)",                          0,                 TYPE_XBOX},
        {0x045e, 0x028e, (char *) "Microsoft X-Box 360 pad",                              0,                 TYPE_XBOX360},
        {0x045e, 0x028f, (char *) "Microsoft X-Box 360 pad v2",                           0,                 TYPE_XBOX360},
        {0x045e, 0x0291, (char *) "Xbox 360 Wireless Receiver (XBOX)",              MAP_DPAD_TO_BUTTONS,     TYPE_XBOX360W},
        {0x045e, 0x02d1, (char *) "Microsoft X-Box One pad",                              0,                 TYPE_XBOXONE},
        {0x045e, 0x02dd, (char *) "Microsoft X-Box One pad (Firmware 2015)",              0,                 TYPE_XBOXONE},
        {0x045e, 0x02e3, (char *) "Microsoft X-Box One Elite pad",                  MAP_PADDLES,             TYPE_XBOXONE},
        {0x045e, 0x0b00, (char *) "Microsoft X-Box One Elite 2 pad",                MAP_PADDLES,             TYPE_XBOXONE},
        {0x045e, 0x02ea, (char *) "Microsoft X-Box One S pad",                            0,                 TYPE_XBOXONE},
        {0x045e, 0x0719, (char *) "Xbox 360 Wireless Receiver",                     MAP_DPAD_TO_BUTTONS,     TYPE_XBOX360W},
        {0x045e, 0x0b0a, (char *) "Microsoft X-Box Adaptive Controller",            MAP_PROFILE_BUTTON,      TYPE_XBOXONE},
        {0x045e, 0x0b12, (char *) "Microsoft Xbox Series S|X Controller",           MAP_SELECT_BUTTON,       TYPE_XBOXONE},
        {0x046d, 0xc21d, (char *) "Logitech Gamepad F310",                                0,                 TYPE_XBOX360},
        {0x046d, 0xc21e, (char *) "Logitech Gamepad F510",                                0,                 TYPE_XBOX360},
        {0x046d, 0xc21f, (char *) "Logitech Gamepad F710",                                0,                 TYPE_XBOX360},
        {0x046d, 0xc242, (char *) "Logitech Chillstream Controller",                      0,                 TYPE_XBOX360},
        {0x046d, 0xca84, (char *) "Logitech Xbox Cordless Controller",                    0,                 TYPE_XBOX},
        {0x046d, 0xca88, (char *) "Logitech Compact Controller for Xbox",                 0,                 TYPE_XBOX},
        {0x046d, 0xca8a, (char *) "Logitech Precision Vibration Feedback Wheel",          0,                 TYPE_XBOX},
        {0x046d, 0xcaa3, (char *) "Logitech DriveFx Racing Wheel",                        0,                 TYPE_XBOX360},
        {0x056e, 0x2004, (char *) "Elecom JC-U3613M",                                     0,                 TYPE_XBOX360},
        {0x05fd, 0x1007, (char *) "Mad Catz Controller (unverified)",                     0,                 TYPE_XBOX},
        {0x05fd, 0x107a, (char *) "InterAct 'PowerPad Pro' X-Box pad (Germany)",          0,                 TYPE_XBOX},
        {0x05fe, 0x3030, (char *) "Chic Controller",                                      0,                 TYPE_XBOX},
        {0x05fe, 0x3031, (char *) "Chic Controller",                                      0,                 TYPE_XBOX},
        {0x062a, 0x0020, (char *) "Logic3 Xbox GamePad",                                  0,                 TYPE_XBOX},
        {0x062a, 0x0033, (char *) "Competition Pro Steering Wheel",                       0,                 TYPE_XBOX},
        {0x06a3, 0x0200, (char *) "Saitek Racing Wheel",                                  0,                 TYPE_XBOX},
        {0x06a3, 0x0201, (char *) "Saitek Adrenalin",                                     0,                 TYPE_XBOX},
        {0x06a3, 0xf51a, (char *) "Saitek P3600",                                         0,                 TYPE_XBOX360},
        {0x0738, 0x4506, (char *) "Mad Catz 4506 Wireless Controller",                    0,                 TYPE_XBOX},
        {0x0738, 0x4516, (char *) "Mad Catz Control Pad",                                 0,                 TYPE_XBOX},
        {0x0738, 0x4520, (char *) "Mad Catz Control Pad Pro",                             0,                 TYPE_XBOX},
        {0x0738, 0x4522, (char *) "Mad Catz LumiCON",                                     0,                 TYPE_XBOX},
        {0x0738, 0x4526, (char *) "Mad Catz Control Pad Pro",                             0,                 TYPE_XBOX},
        {0x0738, 0x4530, (char *) "Mad Catz Universal MC2 Racing Wheel and Pedals",       0,                 TYPE_XBOX},
        {0x0738, 0x4536, (char *) "Mad Catz MicroCON",                                    0,                 TYPE_XBOX},
        {0x0738, 0x4540, (char *) "Mad Catz Beat Pad",                              MAP_DPAD_TO_BUTTONS,     TYPE_XBOX},
        {0x0738, 0x4556, (char *) "Mad Catz Lynx Wireless Controller",                    0,                 TYPE_XBOX},
        {0x0738, 0x4586, (char *) "Mad Catz MicroCon Wireless Controller",                0,                 TYPE_XBOX},
        {0x0738, 0x4588, (char *) "Mad Catz Blaster",                                     0,                 TYPE_XBOX},
        {0x0738, 0x45ff, (char *) "Mad Catz Beat Pad (w/ Handle)",                  MAP_DPAD_TO_BUTTONS,     TYPE_XBOX},
        {0x0738, 0x4716, (char *) "Mad Catz Wired Xbox 360 Controller",                   0,                 TYPE_XBOX360},
        {0x0738, 0x4718, (char *) "Mad Catz Street Fighter IV FightStick SE",             0,                 TYPE_XBOX360},
        {0x0738, 0x4726, (char *) "Mad Catz Xbox 360 Controller",                         0,                 TYPE_XBOX360},
        {0x0738, 0x4728, (char *) "Mad Catz Street Fighter IV FightPad",            MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x0738, 0x4736, (char *) "Mad Catz MicroCon Gamepad",                            0,                 TYPE_XBOX360},
        {0x0738, 0x4738, (char *) "Mad Catz Wired Xbox 360 Controller (SFIV)",      MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x0738, 0x4740, (char *) "Mad Catz Beat Pad",                                    0,                 TYPE_XBOX360},
        {0x0738, 0x4743, (char *) "Mad Catz Beat Pad Pro",                          MAP_DPAD_TO_BUTTONS,     TYPE_XBOX},
        {0x0738, 0x4758, (char *) "Mad Catz Arcade Game Stick",                     MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x0738, 0x4a01, (char *) "Mad Catz FightStick TE 2",                       MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOXONE},
        {0x0738, 0x6040, (char *) "Mad Catz Beat Pad Pro",                          MAP_DPAD_TO_BUTTONS,     TYPE_XBOX},
        {0x0738, 0x9871, (char *) "Mad Catz Portable Drum",                               0,                 TYPE_XBOX360},
        {0x0738, 0xb726, (char *) "Mad Catz Xbox controller - MW2",                       0,                 TYPE_XBOX360},
        {0x0738, 0xb738, (char *) "Mad Catz MVC2TE Stick 2",                        MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x0738, 0xbeef, (char *) "Mad Catz JOYTECH NEO SE Advanced GamePad",       TYPE_XBOX360},
        {0x0738, 0xcb02, (char *) "Saitek Cyborg Rumble Pad - PC/Xbox 360",               0,                 TYPE_XBOX360},
        {0x0738, 0xcb03, (char *) "Saitek P3200 Rumble Pad - PC/Xbox 360",                0,                 TYPE_XBOX360},
        {0x0738, 0xcb29, (char *) "Saitek Aviator Stick AV8R02",                          0,                 TYPE_XBOX360},
        {0x0738, 0xf738, (char *) "Super SFIV FightStick TE S",                           0,                 TYPE_XBOX360},
        {0x07ff, 0xffff, (char *) "Mad Catz GamePad",                                     0,                 TYPE_XBOX360},
        {0x0c12, 0x0005, (char *) "Intec wireless",                                       0,                 TYPE_XBOX},
        {0x0c12, 0x8801, (char *) "Nyko Xbox Controller",                                 0,                 TYPE_XBOX},
        {0x0c12, 0x8802, (char *) "Zeroplus Xbox Controller",                             0,                 TYPE_XBOX},
        {0x0c12, 0x8809, (char *) "RedOctane Xbox Dance Pad",                       DANCEPAD_MAP_CONFIG,     TYPE_XBOX},
        {0x0c12, 0x880a, (char *) "Pelican Eclipse PL-2023",                              0,                 TYPE_XBOX},
        {0x0c12, 0x8810, (char *) "Zeroplus Xbox Controller",                             0,                 TYPE_XBOX},
        {0x0c12, 0x9902, (char *) "HAMA VibraX - *FAULTY HARDWARE*",                      0,                 TYPE_XBOX},
        {0x0d2f, 0x0002, (char *) "Andamiro Pump It Up pad",                        MAP_DPAD_TO_BUTTONS,     TYPE_XBOX},
        {0x0e4c, 0x1097, (char *) "Radica Gamester Controller",                           0,                 TYPE_XBOX},
        {0x0e4c, 0x1103, (char *) "Radica Gamester Reflex",                         MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX},
        {0x0e4c, 0x2390, (char *) "Radica Games Jtech Controller",                        0,                 TYPE_XBOX},
        {0x0e4c, 0x3510, (char *) "Radica Gamester",                                      0,                 TYPE_XBOX},
        {0x0e6f, 0x0003, (char *) "Logic3 Freebird wireless Controller",                  0,                 TYPE_XBOX},
        {0x0e6f, 0x0005, (char *) "Eclipse wireless Controller",                          0,                 TYPE_XBOX},
        {0x0e6f, 0x0006, (char *) "Edge wireless Controller",                             0,                 TYPE_XBOX},
        {0x0e6f, 0x0008, (char *) "After Glow Pro Controller",                            0,                 TYPE_XBOX},
        {0x0e6f, 0x0105, (char *) "HSM3 Xbox360 dancepad",                          MAP_DPAD_TO_BUTTONS,     TYPE_XBOX360},
        {0x0e6f, 0x0113, (char *) "Afterglow AX.1 Gamepad for Xbox 360",                  0,                 TYPE_XBOX360},
        {0x0e6f, 0x011f, (char *) "Rock Candy Gamepad Wired Controller",                  0,                 TYPE_XBOX360},
        {0x0e6f, 0x0131, (char *) "PDP EA Sports Controller",                             0,                 TYPE_XBOX360},
        {0x0e6f, 0x0133, (char *) "Xbox 360 Wired Controller",                            0,                 TYPE_XBOX360},
        {0x0e6f, 0x0139, (char *) "Afterglow Prismatic Wired Controller",                 0,                 TYPE_XBOXONE},
        {0x0e6f, 0x013a, (char *) "PDP Xbox One Controller",                              0,                 TYPE_XBOXONE},
        {0x0e6f, 0x0146, (char *) "Rock Candy Wired Controller for Xbox One",             0,                 TYPE_XBOXONE},
        {0x0e6f, 0x0147, (char *) "PDP Marvel Xbox One Controller",                       0,                 TYPE_XBOXONE},
        {0x0e6f, 0x015c, (char *) "PDP Xbox One Arcade Stick",                      MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOXONE},
        {0x0e6f, 0x0161, (char *) "PDP Xbox One Controller",                              0,                 TYPE_XBOXONE},
        {0x0e6f, 0x0162, (char *) "PDP Xbox One Controller",                              0,                 TYPE_XBOXONE},
        {0x0e6f, 0x0163, (char *) "PDP Xbox One Controller",                              0,                 TYPE_XBOXONE},
        {0x0e6f, 0x0164, (char *) "PDP Battlefield One",                                  0,                 TYPE_XBOXONE},
        {0x0e6f, 0x0165, (char *) "PDP Titanfall 2",                                      0,                 TYPE_XBOXONE},
        {0x0e6f, 0x0201, (char *) "Pelican PL-3601 'TSZ' Wired Xbox 360 Controller",      0,                 TYPE_XBOX360},
        {0x0e6f, 0x0213, (char *) "Afterglow Gamepad for Xbox 360",                       0,                 TYPE_XBOX360},
        {0x0e6f, 0x021f, (char *) "Rock Candy Gamepad for Xbox 360",                      0,                 TYPE_XBOX360},
        {0x0e6f, 0x0246, (char *) "Rock Candy Gamepad for Xbox One 2015",                 0,                 TYPE_XBOXONE},
        {0x0e6f, 0x02a0, (char *) "PDP Xbox One Controller",                              0,                 TYPE_XBOXONE},
        {0x0e6f, 0x02a1, (char *) "PDP Xbox One Controller",                              0,                 TYPE_XBOXONE},
        {0x0e6f, 0x02a2, (char *) "PDP Wired Controller for Xbox One - Crimson Red",      0,                 TYPE_XBOXONE},
        {0x0e6f, 0x02a4, (char *) "PDP Wired Controller for Xbox One - Stealth Series",   0,                 TYPE_XBOXONE},
        {0x0e6f, 0x02a6, (char *) "PDP Wired Controller for Xbox One - Camo Series",      0,                 TYPE_XBOXONE},
        {0x0e6f, 0x02a7, (char *) "PDP Xbox One Controller",                              0,                 TYPE_XBOXONE},
        {0x0e6f, 0x02a8, (char *) "PDP Xbox One Controller",                              0,                 TYPE_XBOXONE},
        {0x0e6f, 0x02ab, (char *) "PDP Controller for Xbox One",                          0,                 TYPE_XBOXONE},
        {0x0e6f, 0x02ad, (char *) "PDP Wired Controller for Xbox One - Stealth Series",   0,                 TYPE_XBOXONE},
        {0x0e6f, 0x02b3, (char *) "Afterglow Prismatic Wired Controller",                 0,                 TYPE_XBOXONE},
        {0x0e6f, 0x02b8, (char *) "Afterglow Prismatic Wired Controller",                 0,                 TYPE_XBOXONE},
        {0x0e6f, 0x0301, (char *) "Logic3 Controller",                                    0,                 TYPE_XBOX360},
        {0x0e6f, 0x0346, (char *) "Rock Candy Gamepad for Xbox One 2016",                 0,                 TYPE_XBOXONE},
        {0x0e6f, 0x0401, (char *) "Logic3 Controller",                                    0,                 TYPE_XBOX360},
        {0x0e6f, 0x0413, (char *) "Afterglow AX.1 Gamepad for Xbox 360",                  0,                 TYPE_XBOX360},
        {0x0e6f, 0x0501, (char *) "PDP Xbox 360 Controller",                              0,                 TYPE_XBOX360},
        {0x0e6f, 0xf900, (char *) "PDP Afterglow AX.1",                                   0,                 TYPE_XBOX360},
        {0x0e8f, 0x0201, (char *) "SmartJoy Frag Xpad/PS2 adaptor",                       0,                 TYPE_XBOX},
        {0x0e8f, 0x3008, (char *) "Generic xbox control (dealextreme)",                   0,                 TYPE_XBOX},
        {0x0f0d, 0x000a, (char *) "Hori Co. DOA4 FightStick",                             0,                 TYPE_XBOX360},
        {0x0f0d, 0x000c, (char *) "Hori PadEX Turbo",                                     0,                 TYPE_XBOX360},
        {0x0f0d, 0x000d, (char *) "Hori Fighting Stick EX2",                        MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x0f0d, 0x0016, (char *) "Hori Real Arcade Pro.EX",                        MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x0f0d, 0x001b, (char *) "Hori Real Arcade Pro VX",                        MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x0f0d, 0x0063, (char *) "Hori Real Arcade Pro Hayabusa (USA) Xbox One",   MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOXONE},
        {0x0f0d, 0x0067, (char *) "HORIPAD ONE",                                          0,                 TYPE_XBOXONE},
        {0x0f0d, 0x0078, (char *) "Hori Real Arcade Pro V Kai Xbox One",            MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOXONE},
        {0x0f0d, 0x00c5, (char *) "Hori Fighting Commander ONE",                    MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOXONE},
        {0x0f30, 0x010b, (char *) "Philips Recoil",                                       0,                 TYPE_XBOX},
        {0x0f30, 0x0202, (char *) "Joytech Advanced Controller",                          0,                 TYPE_XBOX},
        {0x0f30, 0x8888, (char *) "BigBen XBMiniPad Controller",                          0,                 TYPE_XBOX},
        {0x102c, 0xff0c, (char *) "Joytech Wireless Advanced Controller",                 0,                 TYPE_XBOX},
        {0x1038, 0x1430, (char *) "SteelSeries Stratus Duo",                              0,                 TYPE_XBOX360},
        {0x1038, 0x1431, (char *) "SteelSeries Stratus Duo",                              0,                 TYPE_XBOX360},
        {0x11c9, 0x55f0, (char *) "Nacon GC-100XF",                                       0,                 TYPE_XBOX360},
        {0x1209, 0x2882, (char *) "Ardwiino Controller",                                  0,                 TYPE_XBOX360},
        {0x12ab, 0x0004, (char *) "Honey Bee Xbox360 dancepad",                     MAP_DPAD_TO_BUTTONS,     TYPE_XBOX360},
        {0x12ab, 0x0301, (char *) "PDP AFTERGLOW AX.1",                                   0,                 TYPE_XBOX360},
        {0x12ab, 0x0303, (char *) "Mortal Kombat Klassic FightStick",               MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x12ab, 0x8809, (char *) "Xbox DDR dancepad",                              MAP_DPAD_TO_BUTTONS,     TYPE_XBOX},
        {0x1430, 0x4748, (char *) "RedOctane Guitar Hero X-plorer",                       0,                 TYPE_XBOX360},
        {0x1430, 0x8888, (char *) "TX6500+ Dance Pad (first generation)",           MAP_DPAD_TO_BUTTONS,     TYPE_XBOX},
        {0x1430, 0xf801, (char *) "RedOctane Controller",                                 0,                 TYPE_XBOX360},
        {0x146b, 0x0601, (char *) "BigBen Interactive XBOX 360 Controller",               0,                 TYPE_XBOX360},
        {0x146b, 0x0604, (char *) "Bigben Interactive DAIJA Arcade Stick",          MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x1532, 0x0037, (char *) "Razer Sabertooth",                                     0,                 TYPE_XBOX360},
        {0x1532, 0x0a00, (char *) "Razer Atrox Arcade Stick",                       MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOXONE},
        {0x1532, 0x0a03, (char *) "Razer Wildcat",                                        0,                 TYPE_XBOXONE},
        {0x15e4, 0x3f00, (char *) "Power A Mini Pro Elite",                               0,                 TYPE_XBOX360},
        {0x15e4, 0x3f0a, (char *) "Xbox Airflo wired controller",                         0,                 TYPE_XBOX360},
        {0x15e4, 0x3f10, (char *) "Batarang Xbox 360 controller",                         0,                 TYPE_XBOX360},
        {0x162e, 0xbeef, (char *) "Joytech Neo-Se Take2",                                 0,                 TYPE_XBOX360},
        {0x1689, 0xfd00, (char *) "Razer Onza Tournament Edition",                        0,                 TYPE_XBOX360},
        {0x1689, 0xfd01, (char *) "Razer Onza Classic Edition",                           0,                 TYPE_XBOX360},
        {0x1689, 0xfe00, (char *) "Razer Sabertooth",                                     0,                 TYPE_XBOX360},
        {0x1949, 0x041a, (char *) "Amazon Game Controller",                               0,                 TYPE_XBOX360},
        {0x1bad, 0x0002, (char *) "Harmonix Rock Band Guitar",                            0,                 TYPE_XBOX360},
        {0x1bad, 0x0003, (char *) "Harmonix Rock Band Drumkit",                     MAP_DPAD_TO_BUTTONS,     TYPE_XBOX360},
        {0x1bad, 0x0130, (char *) "Ion Drum Rocker",                                MAP_DPAD_TO_BUTTONS,     TYPE_XBOX360},
        {0x1bad, 0xf016, (char *) "Mad Catz Xbox 360 Controller",                         0,                 TYPE_XBOX360},
        {0x1bad, 0xf018, (char *) "Mad Catz Street Fighter IV SE Fighting Stick",   MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x1bad, 0xf019, (char *) "Mad Catz Brawlstick for Xbox 360",               MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x1bad, 0xf021, (char *) "Mad Cats Ghost Recon FS GamePad",                      0,                 TYPE_XBOX360},
        {0x1bad, 0xf023, (char *) "MLG Pro Circuit Controller (Xbox)",                    0,                 TYPE_XBOX360},
        {0x1bad, 0xf025, (char *) "Mad Catz Call Of Duty",                                0,                 TYPE_XBOX360},
        {0x1bad, 0xf027, (char *) "Mad Catz FPS Pro",                                     0,                 TYPE_XBOX360},
        {0x1bad, 0xf028, (char *) "Street Fighter IV FightPad",                           0,                 TYPE_XBOX360},
        {0x1bad, 0xf02e, (char *) "Mad Catz Fightpad",                              MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x1bad, 0xf030, (char *) "Mad Catz Xbox 360 MC2 MicroCon Racing Wheel",          0,                 TYPE_XBOX360},
        {0x1bad, 0xf036, (char *) "Mad Catz MicroCon GamePad Pro",                        0,                 TYPE_XBOX360},
        {0x1bad, 0xf038, (char *) "Street Fighter IV FightStick TE",                      0,                 TYPE_XBOX360},
        {0x1bad, 0xf039, (char *) "Mad Catz MvC2 TE",                               MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x1bad, 0xf03a, (char *) "Mad Catz SFxT Fightstick Pro",                   MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x1bad, 0xf03d, (char *) "Street Fighter IV Arcade Stick TE - Chun Li",    MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x1bad, 0xf03e, (char *) "Mad Catz MLG FightStick TE",                     MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x1bad, 0xf03f, (char *) "Mad Catz FightStick SoulCaliber",                MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x1bad, 0xf042, (char *) "Mad Catz FightStick TES+",                       MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x1bad, 0xf080, (char *) "Mad Catz FightStick TE2",                        MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x1bad, 0xf501, (char *) "HoriPad EX2 Turbo",                                    0,                 TYPE_XBOX360},
        {0x1bad, 0xf502, (char *) "Hori Real Arcade Pro.VX SA",                     MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x1bad, 0xf503, (char *) "Hori Fighting Stick VX",                         MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x1bad, 0xf504, (char *) "Hori Real Arcade Pro. EX",                       MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x1bad, 0xf505, (char *) "Hori Fighting Stick EX2B",                       MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x1bad, 0xf506, (char *) "Hori Real Arcade Pro.EX Premium VLX",                  0,                 TYPE_XBOX360},
        {0x1bad, 0xf900, (char *) "Harmonix Xbox 360 Controller",                         0,                 TYPE_XBOX360},
        {0x1bad, 0xf901, (char *) "Gamestop Xbox 360 Controller",                         0,                 TYPE_XBOX360},
        {0x1bad, 0xf903, (char *) "Tron Xbox 360 controller",                             0,                 TYPE_XBOX360},
        {0x1bad, 0xf904, (char *) "PDP Versus Fighting Pad",                              0,                 TYPE_XBOX360},
        {0x1bad, 0xf906, (char *) "MortalKombat FightStick",                        MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x1bad, 0xfa01, (char *) "MadCatz GamePad",                                      0,                 TYPE_XBOX360},
        {0x1bad, 0xfd00, (char *) "Razer Onza TE",                                        0,                 TYPE_XBOX360},
        {0x1bad, 0xfd01, (char *) "Razer Onza",                                           0,                 TYPE_XBOX360},
        {0x20d6, 0x2001, (char *) "BDA Xbox Series X Wired Controller",                   0,                 TYPE_XBOXONE},
        {0x20d6, 0x2009, (char *) "PowerA Enhanced Wired Controller for Xbox Series X|S", 0,                 TYPE_XBOXONE},
        {0x20d6, 0x281f, (char *) "PowerA Wired Controller For Xbox 360",                 0,                 TYPE_XBOX360},
        {0x2e24, 0x0652, (char *) "Hyperkin Duke X-Box One pad",                          0,                 TYPE_XBOXONE},
        {0x24c6, 0x5000, (char *) "Razer Atrox Arcade Stick",                       MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x24c6, 0x5300, (char *) "PowerA MINI PROEX Controller",                         0,                 TYPE_XBOX360},
        {0x24c6, 0x5303, (char *) "Xbox Airflo wired controller",                         0,                 TYPE_XBOX360},
        {0x24c6, 0x530a, (char *) "Xbox 360 Pro EX Controller",                           0,                 TYPE_XBOX360},
        {0x24c6, 0x531a, (char *) "PowerA Pro Ex",                                        0,                 TYPE_XBOX360},
        {0x24c6, 0x5397, (char *) "FUS1ON Tournament Controller",                         0,                 TYPE_XBOX360},
        {0x24c6, 0x541a, (char *) "PowerA Xbox One Mini Wired Controller",                0,                 TYPE_XBOXONE},
        {0x24c6, 0x542a, (char *) "Xbox ONE spectra",                                     0,                 TYPE_XBOXONE},
        {0x24c6, 0x543a, (char *) "PowerA Xbox One wired controller",                     0,                 TYPE_XBOXONE},
        {0x24c6, 0x5500, (char *) "Hori XBOX 360 EX 2 with Turbo",                        0,                 TYPE_XBOX360},
        {0x24c6, 0x5501, (char *) "Hori Real Arcade Pro VX-SA",                           0,                 TYPE_XBOX360},
        {0x24c6, 0x5502, (char *) "Hori Fighting Stick VX Alt",                     MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x24c6, 0x5503, (char *) "Hori Fighting Edge",                             MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x24c6, 0x5506, (char *) "Hori SOULCALIBUR V Stick",                             0,                 TYPE_XBOX360},
        {0x24c6, 0x5510, (char *) "Hori Fighting Commander ONE (Xbox 360/PC Mode)", MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x24c6, 0x550d, (char *) "Hori GEM Xbox controller",                             0,                 TYPE_XBOX360},
        {0x24c6, 0x550e, (char *) "Hori Real Arcade Pro V Kai 360",                 MAP_TRIGGERS_TO_BUTTONS, TYPE_XBOX360},
        {0x24c6, 0x551a, (char *) "PowerA FUSION Pro Controller",                         0,                 TYPE_XBOXONE},
        {0x24c6, 0x561a, (char *) "PowerA FUSION Controller",                             0,                 TYPE_XBOXONE},
        {0x24c6, 0x5b00, (char *) "ThrustMaster Ferrari 458 Racing Wheel",                0,                 TYPE_XBOX360},
        {0x24c6, 0x5b02, (char *) "Thrustmaster, Inc. GPX Controller",                    0,                 TYPE_XBOX360},
        {0x24c6, 0x5b03, (char *) "Thrustmaster Ferrari 458 Racing Wheel",                0,                 TYPE_XBOX360},
        {0x24c6, 0x5d04, (char *) "Razer Sabertooth",                                     0,                 TYPE_XBOX360},
        {0x24c6, 0xfafe, (char *) "Rock Candy Gamepad for Xbox 360",                      0,                 TYPE_XBOX360},
        {0x2563, 0x058d, (char *) "OneXPlayer Gamepad",                                   0,                 TYPE_XBOX360},
        {0x2dc8, 0x2000, (char *) "8BitDo Pro 2 Wired Controller fox Xbox",               0,                 TYPE_XBOXONE},
        {0x2dc8, 0x3106, (char *) "8BitDo Pro 2 Wired Controller",                        0,                 TYPE_XBOX360},
        {0x31e3, 0x1100, (char *) "Wooting One",                                          0,                 TYPE_XBOX360},
        {0x31e3, 0x1200, (char *) "Wooting Two",                                          0,                 TYPE_XBOX360},
        {0x31e3, 0x1210, (char *) "Wooting Lekker",                                       0,                 TYPE_XBOX360},
        {0x31e3, 0x1220, (char *) "Wooting Two HE",                                       0,                 TYPE_XBOX360},
        {0x31e3, 0x1300, (char *) "Wooting 60HE (AVR)",                                   0,                 TYPE_XBOX360},
        {0x31e3, 0x1310, (char *) "Wooting 60HE (ARM)",                                   0,                 TYPE_XBOX360},
        {0x3285, 0x0607, (char *) "Nacon GC-100",                                         0,                 TYPE_XBOX360},
        {0x3767, 0x0101, (char *) "Fanatec Speedster 3 Forceshock Wheel",                 0,                 TYPE_XBOX},
        {0xffff, 0xffff, (char *) "Chinese-made Xbox Controller",                         0,                 TYPE_XBOX},
        ///
        /// DS4
        ///
        {0x054c, 0x05c4, (char *) "DualShock 4",                                          0,                 TYPE_DS4},
        {0x054c, 0x09cc, (char *) "DualShock 4 (2nd Gen)",                                0,                 TYPE_DS4},
        {0x054c, 0x0ce6, (char *) "DualSense",                                            0,                 TYPE_DS5},
        ///
        /// Unknown
        ///
        {0x0000, 0x0000, (char *) "Unknown device",                                       0,                 TYPE_UNKNOWN},
};

const Device *find_device(uint16_t vid, uint16_t pid) {
    // lookup for a known game controller
    int i = 0;
    int p = INT32_MAX;

    while (p > 0) {
        p = devices[i].idProduct;
        if (p == pid && devices[i].idVendor == vid) {
            return &devices[i];
        }
        i++;
    }

    return nullptr;
}
